package com.example.todo

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity // this table is a part of database
data class ToDoModel(var title : String,
                     var description : String,
                     var category : String,
                     var date : Long,
                     var time : Long,
                     var isFinished : Int = -1,
                     @PrimaryKey(autoGenerate = true)
                     var id: Long = 0) // primary key will be autogenerated